# ===================================================================
#   Master Manifest of Raw Data Sources
#   Project: towardTreeEquity
#   Pilot: NYC Park Cooling Index (PCI)
# ===================================================================

nyc_pci_pilot_sources:

  # --- Single-File Sources (Simple) ---
  - source_id: "lst_median_2022"
    layer_name: "land_surface_temperature"
    description: "Median Land Surface Temperature (LST) Raster Data"
    local_path: "data/bronze/raster/surfacetemperature_median_2020_2022.tif"
    source_type: "raster"
    file_format: "GeoTIFF"
    # No handler needed

  - source_id: "ndvi_median_2022"
    layer_name: "ndvi"
    description: "Median NDVI Raster Data"
    local_path: "data/bronze/raster/NYC_NDVI_2020-2022_Summer_Median.tif"
    source_type: "raster"
    file_format: "GeoTIFF"
    # No handler needed

  # --- Multi-File Sources (Explicit) ---
  - source_id: "parks_nyc_2025"
    layer_name: "urban_parks"
    description: "Polygon properties managed by NYC Parks for geospatial analysis"
    source_directory: "data/bronze/vector/ParkProperties_2025" # Path to the FOLDER
    validation_target: "geo_export_f59d1ffc-ed9b-4275-8c89-9cb8dc88a521.shp"
    source_type: "vector"
    file_format: "Shapefile"
    handler: "zip_folder"

  - source_id: "land_cover_nyc_2017"
    layer_name: "land_cover"
    description: "6-inch resolution 8-class land cover dataset"
    source_directory: "data/bronze/raster/Land_Cover" # Path to the FOLDER
    validation_target: "NYC_2017_LiDAR_LandCover.img" # Main file INSIDE the folder
    source_type: "raster"
    file_format: "Erdas Imagine"
    handler: "zip_folder"

  - source_id: "road_network_lion_2024"
    layer_name: "road_network"
    description: "LION single line street base map"
    source_directory: "data/bronze/vector/RoadLines"
    validation_target: "lion.gdb" # Main dataset INSIDE the folder
    source_type: "vector"
    file_format: "File Geodatabase"
    handler: "zip_folder"
    
  - source_id: "boundary_nyc_2025"
    layer_name: "nyc_borough_boundary"
    description: "New York City borough boundaries"
    source_directory: "data/bronze/vector/nybb_25b" # Path to the FOLDER
    validation_target: "nybb.shp" # Main file INSIDE the folder
    source_type: "vector"
    file_format: "Shapefile"
    handler: "zip_folder"
